import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Toaster } from "sonner"
import GeneralModaler from "../components/customs/custom-modals/general-modal"
import PreferredTheme from "../components/ui/theme/preferred-theme"
import { Prompter } from "../components/ui/use-prompt"
import { cn } from "../utils/tailwind"
import "./globals.css"
import { QueryProvider } from "../lib/query/query"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next.js Shadcn admin starter",
  description: "Generated by Next.js Shadcn admin starter",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(GeistSans.className, "bg-app-background antialiased")}>
        <QueryProvider>
          <PreferredTheme>
            {children}
            <Prompter />
            <Toaster />
            <GeneralModaler />
          </PreferredTheme>
        </QueryProvider>
      </body>
    </html>
  )
}
