/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AdminAdminImport } from './routes/admin/_admin'
import { Route as AdminAdminMainImport } from './routes/admin/_admin._main'
import { Route as AdminAdminEditorImport } from './routes/admin/_admin._editor'
import { Route as AdminAdminMainIndexImport } from './routes/admin/_admin._main/index'
import { Route as AdminAdminMainPostsLayoutImport } from './routes/admin/_admin._main/posts/_layout'
import { Route as AdminAdminMainCategoriesLayoutImport } from './routes/admin/_admin._main/categories/_layout'
import { Route as AdminAdminEditorPostsCreateImport } from './routes/admin/_admin._editor/posts/create'
import { Route as AdminAdminEditorPostsLayoutImport } from './routes/admin/_admin._editor/posts/_layout'
import { Route as AdminAdminMainPostsLayoutIndexImport } from './routes/admin/_admin._main/posts/_layout.index'
import { Route as AdminAdminMainCategoriesLayoutIndexImport } from './routes/admin/_admin._main/categories/_layout.index'
import { Route as AdminAdminEditorPostsLayoutHandlerImport } from './routes/admin/_admin._editor/posts/_layout.$handler'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()
const AboutLazyImport = createFileRoute('/about')()
const AdminAdminMainPostsImport = createFileRoute('/admin/_admin/_main/posts')()
const AdminAdminMainCategoriesImport = createFileRoute(
  '/admin/_admin/_main/categories',
)()
const AdminAdminEditorPostsImport = createFileRoute(
  '/admin/_admin/_editor/posts',
)()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminRoute = AdminAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAdminMainRoute = AdminAdminMainImport.update({
  id: '/_main',
  getParentRoute: () => AdminAdminRoute,
} as any)

const AdminAdminEditorRoute = AdminAdminEditorImport.update({
  id: '/_editor',
  getParentRoute: () => AdminAdminRoute,
} as any)

const AdminAdminMainPostsRoute = AdminAdminMainPostsImport.update({
  path: '/posts',
  getParentRoute: () => AdminAdminMainRoute,
} as any)

const AdminAdminMainCategoriesRoute = AdminAdminMainCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => AdminAdminMainRoute,
} as any)

const AdminAdminEditorPostsRoute = AdminAdminEditorPostsImport.update({
  path: '/posts',
  getParentRoute: () => AdminAdminEditorRoute,
} as any)

const AdminAdminMainIndexRoute = AdminAdminMainIndexImport.update({
  path: '/',
  getParentRoute: () => AdminAdminMainRoute,
} as any)

const AdminAdminMainPostsLayoutRoute = AdminAdminMainPostsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AdminAdminMainPostsRoute,
} as any)

const AdminAdminMainCategoriesLayoutRoute =
  AdminAdminMainCategoriesLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AdminAdminMainCategoriesRoute,
  } as any)

const AdminAdminEditorPostsCreateRoute =
  AdminAdminEditorPostsCreateImport.update({
    path: '/create',
    getParentRoute: () => AdminAdminEditorPostsRoute,
  } as any)

const AdminAdminEditorPostsLayoutRoute =
  AdminAdminEditorPostsLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => AdminAdminEditorPostsRoute,
  } as any)

const AdminAdminMainPostsLayoutIndexRoute =
  AdminAdminMainPostsLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AdminAdminMainPostsLayoutRoute,
  } as any)

const AdminAdminMainCategoriesLayoutIndexRoute =
  AdminAdminMainCategoriesLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AdminAdminMainCategoriesLayoutRoute,
  } as any)

const AdminAdminEditorPostsLayoutHandlerRoute =
  AdminAdminEditorPostsLayoutHandlerImport.update({
    path: '/$handler',
    getParentRoute: () => AdminAdminEditorPostsLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/_admin': {
      preLoaderRoute: typeof AdminAdminImport
      parentRoute: typeof AdminRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/_admin/_editor': {
      preLoaderRoute: typeof AdminAdminEditorImport
      parentRoute: typeof AdminAdminImport
    }
    '/admin/_admin/_main': {
      preLoaderRoute: typeof AdminAdminMainImport
      parentRoute: typeof AdminAdminImport
    }
    '/admin/_admin/_main/': {
      preLoaderRoute: typeof AdminAdminMainIndexImport
      parentRoute: typeof AdminAdminMainImport
    }
    '/admin/_admin/_editor/posts': {
      preLoaderRoute: typeof AdminAdminEditorPostsImport
      parentRoute: typeof AdminAdminEditorImport
    }
    '/admin/_admin/_editor/posts/_layout': {
      preLoaderRoute: typeof AdminAdminEditorPostsLayoutImport
      parentRoute: typeof AdminAdminEditorPostsRoute
    }
    '/admin/_admin/_editor/posts/create': {
      preLoaderRoute: typeof AdminAdminEditorPostsCreateImport
      parentRoute: typeof AdminAdminEditorPostsImport
    }
    '/admin/_admin/_main/categories': {
      preLoaderRoute: typeof AdminAdminMainCategoriesImport
      parentRoute: typeof AdminAdminMainImport
    }
    '/admin/_admin/_main/categories/_layout': {
      preLoaderRoute: typeof AdminAdminMainCategoriesLayoutImport
      parentRoute: typeof AdminAdminMainCategoriesRoute
    }
    '/admin/_admin/_main/posts': {
      preLoaderRoute: typeof AdminAdminMainPostsImport
      parentRoute: typeof AdminAdminMainImport
    }
    '/admin/_admin/_main/posts/_layout': {
      preLoaderRoute: typeof AdminAdminMainPostsLayoutImport
      parentRoute: typeof AdminAdminMainPostsRoute
    }
    '/admin/_admin/_editor/posts/_layout/$handler': {
      preLoaderRoute: typeof AdminAdminEditorPostsLayoutHandlerImport
      parentRoute: typeof AdminAdminEditorPostsLayoutImport
    }
    '/admin/_admin/_main/categories/_layout/': {
      preLoaderRoute: typeof AdminAdminMainCategoriesLayoutIndexImport
      parentRoute: typeof AdminAdminMainCategoriesLayoutImport
    }
    '/admin/_admin/_main/posts/_layout/': {
      preLoaderRoute: typeof AdminAdminMainPostsLayoutIndexImport
      parentRoute: typeof AdminAdminMainPostsLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AboutLazyRoute,
  AdminRoute.addChildren([
    AdminAdminRoute.addChildren([
      AdminAdminEditorRoute.addChildren([
        AdminAdminEditorPostsRoute.addChildren([
          AdminAdminEditorPostsLayoutRoute.addChildren([
            AdminAdminEditorPostsLayoutHandlerRoute,
          ]),
          AdminAdminEditorPostsCreateRoute,
        ]),
      ]),
      AdminAdminMainRoute.addChildren([
        AdminAdminMainIndexRoute,
        AdminAdminMainCategoriesRoute.addChildren([
          AdminAdminMainCategoriesLayoutRoute.addChildren([
            AdminAdminMainCategoriesLayoutIndexRoute,
          ]),
        ]),
        AdminAdminMainPostsRoute.addChildren([
          AdminAdminMainPostsLayoutRoute.addChildren([
            AdminAdminMainPostsLayoutIndexRoute,
          ]),
        ]),
      ]),
    ]),
  ]),
  LoginIndexRoute,
])

/* prettier-ignore-end */
