/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminMainImport } from './routes/admin/_main'
import { Route as AdminEditorImport } from './routes/admin/_editor'
import { Route as AdminMainIndexImport } from './routes/admin/_main/index'
import { Route as AdminMainPostsLayoutImport } from './routes/admin/_main/posts/_layout'
import { Route as AdminMainCategoriesLayoutImport } from './routes/admin/_main/categories/_layout'
import { Route as AdminEditorPostsCreateImport } from './routes/admin/_editor/posts/create'
import { Route as AdminEditorPostsLayoutImport } from './routes/admin/_editor/posts/_layout'
import { Route as AdminMainPostsLayoutIndexImport } from './routes/admin/_main/posts/_layout.index'
import { Route as AdminMainCategoriesLayoutIndexImport } from './routes/admin/_main/categories/_layout.index'
import { Route as AdminEditorPostsLayoutHandlerImport } from './routes/admin/_editor/posts/_layout.$handler'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()
const AboutLazyImport = createFileRoute('/about')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const AdminMainPostsImport = createFileRoute('/admin/_main/posts')()
const AdminMainCategoriesImport = createFileRoute('/admin/_main/categories')()
const AdminEditorPostsImport = createFileRoute('/admin/_editor/posts')()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const AdminMainRoute = AdminMainImport.update({
  id: '/_main',
  getParentRoute: () => AdminRoute,
} as any)

const AdminEditorRoute = AdminEditorImport.update({
  id: '/_editor',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMainPostsRoute = AdminMainPostsImport.update({
  path: '/posts',
  getParentRoute: () => AdminMainRoute,
} as any)

const AdminMainCategoriesRoute = AdminMainCategoriesImport.update({
  path: '/categories',
  getParentRoute: () => AdminMainRoute,
} as any)

const AdminEditorPostsRoute = AdminEditorPostsImport.update({
  path: '/posts',
  getParentRoute: () => AdminEditorRoute,
} as any)

const AdminMainIndexRoute = AdminMainIndexImport.update({
  path: '/',
  getParentRoute: () => AdminMainRoute,
} as any)

const AdminMainPostsLayoutRoute = AdminMainPostsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AdminMainPostsRoute,
} as any)

const AdminMainCategoriesLayoutRoute = AdminMainCategoriesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AdminMainCategoriesRoute,
} as any)

const AdminEditorPostsCreateRoute = AdminEditorPostsCreateImport.update({
  path: '/create',
  getParentRoute: () => AdminEditorPostsRoute,
} as any)

const AdminEditorPostsLayoutRoute = AdminEditorPostsLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AdminEditorPostsRoute,
} as any)

const AdminMainPostsLayoutIndexRoute = AdminMainPostsLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AdminMainPostsLayoutRoute,
} as any)

const AdminMainCategoriesLayoutIndexRoute =
  AdminMainCategoriesLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AdminMainCategoriesLayoutRoute,
  } as any)

const AdminEditorPostsLayoutHandlerRoute =
  AdminEditorPostsLayoutHandlerImport.update({
    path: '/$handler',
    getParentRoute: () => AdminEditorPostsLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/_editor': {
      preLoaderRoute: typeof AdminEditorImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_main': {
      preLoaderRoute: typeof AdminMainImport
      parentRoute: typeof AdminImport
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/_main/': {
      preLoaderRoute: typeof AdminMainIndexImport
      parentRoute: typeof AdminMainImport
    }
    '/admin/_editor/posts': {
      preLoaderRoute: typeof AdminEditorPostsImport
      parentRoute: typeof AdminEditorImport
    }
    '/admin/_editor/posts/_layout': {
      preLoaderRoute: typeof AdminEditorPostsLayoutImport
      parentRoute: typeof AdminEditorPostsRoute
    }
    '/admin/_editor/posts/create': {
      preLoaderRoute: typeof AdminEditorPostsCreateImport
      parentRoute: typeof AdminEditorPostsImport
    }
    '/admin/_main/categories': {
      preLoaderRoute: typeof AdminMainCategoriesImport
      parentRoute: typeof AdminMainImport
    }
    '/admin/_main/categories/_layout': {
      preLoaderRoute: typeof AdminMainCategoriesLayoutImport
      parentRoute: typeof AdminMainCategoriesRoute
    }
    '/admin/_main/posts': {
      preLoaderRoute: typeof AdminMainPostsImport
      parentRoute: typeof AdminMainImport
    }
    '/admin/_main/posts/_layout': {
      preLoaderRoute: typeof AdminMainPostsLayoutImport
      parentRoute: typeof AdminMainPostsRoute
    }
    '/admin/_editor/posts/_layout/$handler': {
      preLoaderRoute: typeof AdminEditorPostsLayoutHandlerImport
      parentRoute: typeof AdminEditorPostsLayoutImport
    }
    '/admin/_main/categories/_layout/': {
      preLoaderRoute: typeof AdminMainCategoriesLayoutIndexImport
      parentRoute: typeof AdminMainCategoriesLayoutImport
    }
    '/admin/_main/posts/_layout/': {
      preLoaderRoute: typeof AdminMainPostsLayoutIndexImport
      parentRoute: typeof AdminMainPostsLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AboutLazyRoute,
  AdminRoute.addChildren([
    AdminEditorRoute.addChildren([
      AdminEditorPostsRoute.addChildren([
        AdminEditorPostsLayoutRoute.addChildren([
          AdminEditorPostsLayoutHandlerRoute,
        ]),
        AdminEditorPostsCreateRoute,
      ]),
    ]),
    AdminMainRoute.addChildren([
      AdminMainIndexRoute,
      AdminMainCategoriesRoute.addChildren([
        AdminMainCategoriesLayoutRoute.addChildren([
          AdminMainCategoriesLayoutIndexRoute,
        ]),
      ]),
      AdminMainPostsRoute.addChildren([
        AdminMainPostsLayoutRoute.addChildren([AdminMainPostsLayoutIndexRoute]),
      ]),
    ]),
  ]),
  LoginIndexLazyRoute,
])

/* prettier-ignore-end */
