import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next.js Shadcn admin starter",
  description: "Generated by Next.js Shadcn admin starter",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={(inter.className, "bg-app-background antialiased")}>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
