/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n"

export type I18nTranslations = {
  messages: {
    hello: string
    PRODUCT: {
      NEW: string
    }
    ENGLISH: string
    ARRAY: [string, string, string]
    cat: string
    cat_name: string
    "set-up-password": {
      heading: string
      title: string
      followLink: string
    }
    day_interval: {
      one: string
      other: string
      zero: string
    }
    nested: string
  }
}
export type I18nPath = Path<I18nTranslations>
