export const GENERAL_MESSAGES = {
  INTERNAL_SERVER_ERROR: "Internal server error occurred.",
  UNAUTHORIZED: "Unauthorized access. Please login.",
  FORBIDDEN: "Access to the requested resource is forbidden.",
  NOT_FOUND: "Requested resource not found.",
  BAD_REQUEST: "Bad request. Please check your request parameters.",
  VALIDATION_ERROR: "Validation failed. Please check your input data.",
  DUPLICATE_ENTRY: "Duplicate entry found.",
  INVALID_CREDENTIALS: "Invalid credentials.",
  OPERATION_NOT_PERMITTED: "Operation not permitted.",
  RESOURCE_CONFLICT: "Resource conflict occurred.",
  INSUFFICIENT_PERMISSIONS: "Insufficient permissions to perform this action.",
  USER_NOT_FOUND: "User not found.",
  TOKEN_EXPIRED: "Token has expired.",
  TOKEN_INVALID: "Invalid token provided.",
  TOKEN_REQUIRED: "Authorization token is required.",
  PASSWORD_RESET_LINK_EXPIRED: "Password reset link has expired.",
  PASSWORD_RESET_LINK_INVALID: "Invalid password reset link.",
  PASSWORD_WEAK: "Password is too weak.",
  SOMETHING_WENT_WRONG: "Oops! Something went wrong.",
  EMAIL_ALREADY_EXISTS: "Email already exists.",
  INVALID_EMAIL_FORMAT: "Invalid email format.",
  INVALID_PASSWORD_FORMAT: "Invalid password format.",
  PASSWORD_MISMATCH: "Passwords do not match.",
  FILE_UPLOAD_FAILED: "Failed to upload file.",
  FILE_NOT_FOUND: "File not found.",
  MAX_UPLOAD_SIZE_EXCEEDED: "Max upload size exceeded.",
  INVALID_FILE_FORMAT: "Invalid file format.",
  INVALID_OPERATION: "Invalid operation.",
  EXTERNAL_API_ERROR: "Error while communicating with external API.",
  SUCCESS: "Operation completed successfully.",
}
